steps:

  - command:
      - bash scripts/build_demo.sh
    label: "Build Demo"
    artifact_paths: "compile_commands.json"

  - command:
      - bash scripts/run_tests.sh
    label: "Ceedling Tests"
    artifact_paths:
      - build/artifacts/gcov/sonar_coverage.xml

  - wait

  - command:
      - buildkite-agent artifact download "compile_commands.json" .
      - buildkite-agent artifact download "build/artifacts/gcov/sonar_coverage.xml" .
      - bash scripts/run_analysis.sh
    label: "SonarCloud Analysis"
