steps:

  - command:
      - bash scripts/build_embedded_demo.sh
    label: "Build embedded demo"
    artifact_paths: "build/compile_commands.json"

  - command:
    - bash scripts/build_desktop_demo.sh

  - command:
      - bash scripts/run_tests.sh
    label: "Ceedling Tests"
    artifact_paths:
      - build/artifacts/gcov/sonar_coverage.xml

  - wait

  - command:
      - buildkite-agent artifact download "build/compile_commands.json" .
      - bash scripts/run_analysis.sh
    label: "SonarCloud Analysis"
    env:
      SONAR_TOKEN: "80641e654940ef85318f565a7692fee00e4e01d8"
