steps:

  - command:
      - bash scripts/build_demo.sh
    label: "Build Demo"
    artifact_paths: "compile_commands.json"

  - command:
    - bash scripts/build_desktop_demo.sh

  - command:
      - bash scripts/run_tests.sh
    label: "Ceedling Tests"
    artifact_paths:
      - build/artifacts/gcov/sonar_coverage.xml

  - wait

  - command:
      - buildkite-agent artifact download "compile_commands.json" .
      - buildkite-agent artifact download "build/artifacts/gcov/sonar_coverage.xml" .
      - bash scripts/run_analysis.sh
    label: "SonarCloud Analysis"
    env:
      SONAR_TOKEN: "80641e654940ef85318f565a7692fee00e4e01d8"
